# Render compatible port
server.port=${PORT:8080}

# Session
server.servlet.session.timeout=2m

# Static files
spring.web.resources.static-locations=classpath:/static/

# (optional tracing remove cheyyachu but okay unte vadachu)
management.tracing.enabled=true
management.tracing.sampling.portability=1.0
